### ISSUE TITLE
Various XDK Samples

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#146] opened 2017-08-15 13:47 UTC
_From @Voxel9 on April 2, 2017 8:59_

All XDK Samples listed in this issue's title (and probably more) will boot without any issues, albeit broken graphics, in cdc5d5cd and older commits. However, as of ecded47 these samples seem to no longer boot at all; only exceptions occur.

Example of the Gamepad sample working on the former, then being unable to boot on the latter:
![image](https://cloud.githubusercontent.com/assets/16278868/24585511/17aa076c-1784-11e7-90d7-98f6a1dfcc5f.png)

![image](https://cloud.githubusercontent.com/assets/16278868/24585679/464846b6-1788-11e7-944b-123e9245be20.png)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/888270/KrnlDebug.txt) (KrnlDebug log for ecded47 build)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#316_

**Comment by PatrickvL** [comment] 2017-08-15 13:47
It's quite strange how an improvement in memory querying seems to lead to not booting these XDK samples anymore. Are you sure it's that exact commit that broke it?

**Comment by PatrickvL** [comment] 2017-08-15 13:47
I suspect these regressions are actually caused by one of the OOVPA changes @jarupxx made. I'm sure this will be corrected soon enough.

**Comment by PatrickvL** [comment] 2017-08-15 13:47
_From @Voxel9 on April 12, 2017 19:40_

I tested jarupxx's last commit before your MemoryManager improvement, and can confirm that the XDK Samples could boot just fine, so yeah, I am certain that the exact commit was ecded47.

**Comment by PatrickvL** [comment] 2017-08-15 13:47
Okay, thanks for verifying that. To be absolutely clear - is this https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/ad659ca408a99870d0b1d6e4e6e3e1c2e8d5b535 the commit in which the XDK samples still ran?

**Comment by PatrickvL** [comment] 2017-08-15 13:47
_From @Voxel9 on April 12, 2017 19:49_

Yes, that's the one :)

**Comment by PatrickvL** [comment] 2017-08-15 13:47
_From @LukeUsher on April 12, 2017 19:53_

I'll do some hardware testing of the memory manager behavior next week, see if the results from Cxbx and real hardware differ.

**Comment by PatrickvL** [comment] 2017-08-15 13:47
Perhaps QueryAllocationSize shouldn't return remaining size in bytes, but something else, like remaining size in pages, or the size of the original allocation (either in bytes or in pages), or the base address of the allocation, or even something more obscure?

**Comment by PatrickvL** [comment] 2017-08-15 13:47
_From @LukeUsher on April 12, 2017 20:1_

My plan is to allocate some memory via various methods, one being MmAllocateContiguousMemory, run QueryAllocationSize on them, dump the results to a text file on the HDD then compare the text files generated by Cxbx-Reloaded and real hardware, that should provide some pointers on what we're doing wrong

**Comment by PatrickvL** [comment] 2017-08-15 13:47
Btw, thanks @Voxel9, for bringing this under our attention, as it's exactly the little things like this, that will truly get us accurate emulation - it's much appreciated!

**Comment by PatrickvL** [comment] 2017-08-15 13:47
_From @LukeUsher on April 12, 2017 20:13_

I believe that MmQueryAllocationSize returns the total size (in bytes) of the pages used by the memory region pointed to by the input. Rather than calculate the remaining size of the buffer and return that, I believe that it finds the base address of the allocation.

Eg. MmAllocateContiguousMemory(0x1000) returns 0x8001000.

MmQueryAllocationSize(0x8001050) would look through a page table (or our memory block info), find the page that contains this address, and return the total size of the pages the allocation uses (in this case 0x1000). Currently we return the remaining space in the page.

Just something to play with until I find time for the HW testing

**Comment by PatrickvL** [comment] 2017-08-15 13:47
_From @LukeUsher on April 12, 2017 20:16_

Update: changing
```ret = info->block.size - ((size_t)addr - (size_t)info->block.addr);```
to 
```ret = info->block.size;```

Fixed the GamePad sample for me.

**Comment by PatrickvL** [comment] 2017-08-15 13:47
@Voxel9 Can you verify that PR #363 fixed these samples' regressions for you too?

**Comment by PatrickvL** [comment] 2017-08-15 13:47
@LukeUsher I'm still interested to see what would be returned if the call mentioned an address from a page after the starting page

**Comment by PatrickvL** [comment] 2017-08-15 13:47
_From @LukeUsher on April 12, 2017 21:25_

That's what the hardware testing will hopefully discover

**Comment by PatrickvL** [comment] 2017-08-15 13:47
_From @ObiKKa on April 12, 2017 22:24_

I've tested it. I was able to boot it up with the latest master build. But original poster above should do likewise. The D-Pad controls didn't work on the main menu. So I entered the Gamepad screen and saw this shot below. I think graphics seem to be missing in the center - I can only see the ring which moves when I use the left analog stick buttons on my keyboard. Right analog stick's button presses worked also but seemed to be slow to register on the screen's text lines perhaps.

![2017-04-13 _first-test](https://cloud.githubusercontent.com/assets/18428108/24981951/4d6037ea-2022-11e7-96e5-831a40da4b64.png)

Also tried the Hardware Video mode. The analog nub is emulated a bit better, more surfaces showing. But broken in two pieces in the middle.
![2017-04-13 _first-test_hardware-video](https://cloud.githubusercontent.com/assets/18428108/24982159/583367cc-2023-11e7-95d1-f75b2c7b2588.png)

[KrnlDebug_(2017-04-13).txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/918017/KrnlDebug_.2017-04-13.txt)

**Comment by PatrickvL** [comment] 2017-08-15 13:47
_From @Voxel9 on April 13, 2017 6:22_

Yep, can confirm the majority of the regressions have been fixed. But a lot of the graphics seem to have broken since they were last working, especially in the 4627 samples (probably side-effects of previous commits); the 5849 samples seem to have remained the same though.

Dolphin (4627) **Before fix:**
![image](https://cloud.githubusercontent.com/assets/16278868/24992169/ce6cbdb4-2017-11e7-9108-a622c2a4ed80.png)

Dolphin (4627) **After fix:**
![image](https://cloud.githubusercontent.com/assets/16278868/24992034/edf12e5a-2016-11e7-9293-f12c20fa0f28.png)

FuzzyTeapot (4627) **Before fix:**
![image](https://cloud.githubusercontent.com/assets/16278868/24992522/c08fa65a-2019-11e7-8c52-586ce28867c2.png)

FuzzyTeapot (4627) **After fix:**
![image](https://cloud.githubusercontent.com/assets/16278868/24992548/e4516f60-2019-11e7-9610-911898fdca6e.png)


As for Gamepad, it seems that both 4627 and 4134 end up displaying none of the gamepad model at all anymore for me:

Gamepad (4627/4134) **Before fix:**
![image](https://cloud.githubusercontent.com/assets/16278868/24992240/3a915612-2018-11e7-8f82-850604d2878b.png)

Gamepad (4627/4134) **After fix:**
![image](https://cloud.githubusercontent.com/assets/16278868/24992269/5ddbeb0a-2018-11e7-8191-e74bc04baa54.png)

Only thing I have noticed is that Fire (5849) still seems to be in regression, hence why I said the majority of the samples no longer regress.

**Comment by PatrickvL** [comment] 2017-08-15 13:47
_From @LukeUsher on April 13, 2017 7:16_

Still investigating, but the graphical corruption in the XDK samples seems to have started when we introduced the Memory Manager. It would seem there is still something we don't have quite right yet. Perhaps we really do need to implement emulated page tables.

**Comment by PatrickvL** [comment] 2017-08-15 13:47
@LukeUsher The most important change the introduction of the new memory manager brought, is that since then addresses in contiguous memory (0x80000000 and up) are returned - this could lead to new code-paths being taken, perhaps even conversion back to non-GPU addresses (by anding with 0x7FFFFFFF) for some operations. If that's the case, we should devise a solution that would map these addresses to the same data. For that, memory-mapped files could be a solution, as those can be mapped onto multiple virtual memory addresses. For this we do need to use an address-range that's both available _with_ **and** _without_ the high-bit set.

**Comment by PatrickvL** [comment] 2017-08-15 13:47
_From @LukeUsher on April 13, 2017 7:42_

Mapping these same addresses is not really possible, eg: 0x80010000 would be 0x00010000, which resides within our XBE, also I don't think this is the issues (although it could be related, we possibly still have some code laying around in Cxbx that makes the < 0x80000000 assumption.

**Comment by PatrickvL** [comment] 2017-08-15 13:47
But we could raise the addresses in the 0x80000000 range up with 128MB, which would circumvent this problem.

**Comment by PatrickvL** [comment] 2017-08-15 13:47
_From @BenNottelling on August 1, 2017 7:19_

Is this still a valid issue?

**Comment by PatrickvL** [comment] 2017-08-15 13:47
XDK Samples and Tutorials are (and will stay) a very important "first-line-of-defense" test-set, as these are small (so can be ran through quickly) and use various methods of rendering. Our focus should be to get them all running flawlessly, as that will significantly raise the quality of larger executables too.

**Comment by PatrickvL** [comment] 2017-08-15 13:47
_From @BenNottelling on August 1, 2017 8:29_

@PatrickvL Haha I'm just asking if these still have regressed I know these are important :)

**Comment by PatrickvL** [comment] 2017-08-15 13:47
@BenNottelling As far as I know, these are still regressed. I've added the "high-priority" label to this issue, as for all issues marked with "regression", this is the most important one.

**Comment by ObiKKa** [comment] 2017-10-18 17:18
Since only this page shows earlier Dolphin screens unlike two other open pages with similar headings I'll post the video here.

This [video](https://www.youtube.com/watch?v=A2WbVVnGvdE) from Literalmente{Game} (Oct 17, 2017) shows a nice running slide-by-slide comparison video for the Dolphin application on two different versions [Master [853eea7b](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/764) and Patrick's WIP LessVertexPatching [c12ac57](https://github.com/PatrickvL/Cxbx-Reloaded/commit/24fc34b4e5dd0e1c7966dd2ea1ad5edcde4fd346)].

Speed is good.

**Comment by ergo720** [comment] 2017-12-29 14:31
Dolphin is perfect, the only issue is that the ingame fps counter reports 15.75 - 15.80 FPS, whereas ours says it's 60
Version https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/b5a3d23fc863b2ba52a3e02033983958209d4083
[Dolphin Demos-10576a01.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1593265/Dolphin.Demos-10576a01.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1593266/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1593267/Xbe.txt)
![capture](https://user-images.githubusercontent.com/30000751/34439299-2f171ea4-ecad-11e7-8a2a-efeef9f80ce6.PNG)

**Comment by Voxel9** [comment] 2017-12-29 14:42
Great to hear 5849 Dolphin has improved! Unfortunately the 4627 version seems to be having some trouble though... 😕

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1593296/Xbe.txt)
[Dolphin-39abbe85.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1593299/Dolphin-39abbe85.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1593297/KrnlDebug.txt)

```
---------------------------
Cxbx-Reloaded
---------------------------
Received Exception Code 0xC0000005 @ EIP := 0x5890C57C

  Press "OK" to terminate emulation.
  Press "Cancel" to debug.
---------------------------
OK   Cancel   
---------------------------
```

**Comment by Voxel9** [comment] 2018-01-04 16:15
It appears that almost none of the XDK samples from 4627, 5933, or 4361 are working anymore. The only sample I tested which still works, but with broken shaders, is the gamepad sample from 4531. I provided some XBE dumps and KrnlDebug logs if it can help at all.

DolphinClassic (4627)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1603864/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1603865/Xbe.txt)

DolphinClassic (5933)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1603872/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1603873/Xbe.txt)

VertexShader (4627)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1603903/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1603904/Xbe.txt)

Fire (4361)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1603912/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1603913/Xbe.txt)

Gamepad (4531) (Doesn't Crash, but shaders seem to be broken)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1603891/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1603892/Xbe.txt)
![image](https://user-images.githubusercontent.com/16278868/34572451-562cbc22-f169-11e7-92d5-2b519632f298.png)

**Comment by LukeUsher** [comment] 2018-01-04 16:53
And yet at the same time, we're showing better progress than ever in many titles, rather odd.
I'll look into it.

**Comment by ObiKKa** [comment] 2018-01-05 02:08
By the way, you should link up this gif!

https://getyarn.io/yarn-clip/12dd3ef3-936d-478f-803e-fd0ac4459cf5/gif

**Comment by haxar** [comment] 2018-01-06 09:38
@PatrickvL et al.

Is the `MmQueryAllocationSize` fix currently not causing regressions in the XDK samples? Still works?:

> changing
> `ret = info->block.size - ((size_t)addr - (size_t)info->block.addr);`
> to
> `ret = info->block.size;`
> 
> Fixed the GamePad sample for me.

I came to the same conclusion when finding out what `MmQueryAllocationSize` returns, when passed a valid `BaseAddress` that may be offset. Need a test case.

BTW, POSIX doesn't have an interface for this Windows call. The caller should keep the allocation size, as it's best programming practice.

**Comment by PatrickvL** [comment] 2018-01-06 10:26
@haxar Well, we can't really change the fact that the Xbox kernel contains a `MmQueryAllocationSize` API which is actively being used by Xbox software titles. So our HLE code does nothing it of the ordinary when calling it too. But, now the new memory manager is in, this is one of the API's that will have to be reconsidered. We're still not entirely clear as to how it should really work. And there's the issue of GPU resource buffers that are accessible to the CPU simply by setting the high bit - that means those pages need to be "identity-mapped" and I'm not sure this already works reliably right now...

**Comment by PatrickvL** [comment] 2018-01-06 11:54
I've checked. Identity-mapping on contiguous memory allocations should work.

**Comment by jarupxx** [comment] 2018-01-09 11:21
Tested with https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/0709152531e62622d2033b3efb5e34b10a2fd4e2
Gamepad works again!

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1614871/KrnlDebug.txt)
![07091525](https://user-images.githubusercontent.com/20138367/34718407-dd1ee6f6-f579-11e7-8c7a-75cef33f30fd.jpg)

**Comment by Voxel9** [comment] 2018-01-09 15:54
That's great news, but I haven't a clue why it still isn't working for me... I deleted my entire Cxbx folder from Appdata and tried again, but still no luck. I'm also using Cxbx-Reloaded/Cxbx-Reloaded@0709152

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1615695/KrnlDebug.txt)

```
---------------------------
Cxbx-Reloaded
---------------------------
Received Exception Code 0xC0000005 @ EIP := 0x040594B3

  Press "OK" to terminate emulation.
  Press "Cancel" to debug.
---------------------------
OK   Cancel   
---------------------------
```

**Comment by PatrickvL** [comment] 2018-01-09 17:20
Another good test case is the cartoon sample

**Comment by Voxel9** [comment] 2018-01-15 09:45
Samples are working again! \o/

MirrorClip 4627
![image](https://user-images.githubusercontent.com/16278868/34936180-49909a70-f9d8-11e7-9e50-b63cdcdd979b.png)

Cartoon 4627
![image](https://user-images.githubusercontent.com/16278868/34936195-5fb64e8a-f9d8-11e7-9317-f062e7264c19.png)

TechCertGame 4631
![image](https://user-images.githubusercontent.com/16278868/34936282-b8490312-f9d8-11e7-84ce-c720f0955645.png)

And so on and so forth...

**Comment by Voxel9** [comment] 2018-01-15 09:58
Sorry for the double post, but I only just realized that the Minnaert sample also boots now:

![image](https://user-images.githubusercontent.com/16278868/34936836-b27e6c68-f9da-11e7-9a5d-f30d91e0f600.png)

**Comment by LukeUsher** [comment] 2018-01-15 10:10
I think it would be better to close this issue and create a different issue for each individual XDK sample, they are different pieces of software afterall. We don't/won't have a generic "homebrew games" or "emulator" issue, so why should XDK samples be any different?

This would be easier to manage too, as we could discuss issues that effect individual XDK samples much more cleanly.

**Comment by Voxel9** [comment] 2018-01-15 10:15
There are so many XDK samples to cover though. I mean, I'd be happy to go through making issues for many of them right now, but wouldn't it clutter up the issue tracker?

**Comment by LukeUsher** [comment] 2018-01-15 10:32
At the end of the day, they are still unique pieces of software. There are a lot of them, but they're not part of a compilation or anything, they're entirely separate. But I understand what you mean, it would make a lot of issues...

I just think the current way of discussing them all in this issue doesn't work too good: There's too much information and things get lost, and when you read a comment it's not always clear which XDK sample it applies to.

**Comment by Voxel9** [comment] 2018-01-15 10:36
Completely understand and couldn't agree more with you.

Alright, so I'll close this issue now, and any issues or regressions with any specific samples in due course I'll make an issue for.

**Closed by Voxel9** 2018-01-15 10:36 UTC
Labels: issue-regression, type-sample, xbe-dump-needed, xdk-4361, xdk-4531, xdk-4627, xdk-5849, xdk-5933
