### ISSUE TITLE
UnleashX Xbox Launcher [9E115330]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#35] opened 2017-08-15 11:09 UTC
_From @fatjohnny118 on August 9, 2017 2:22_

[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210104/CxbxDebug.txt)
<img width="960" alt="dxbx" src="https://user-images.githubusercontent.com/26704355/29102552-ef1e779c-7c87-11e7-96b1-dec0908a72c0.PNG">
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210105/KrnlDebug.txt)
xbe dump below
[9 in 1.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213204/9.in.1.txt)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#631_

**Comment by PatrickvL** [comment] 2017-08-18 11:23
Title was : "9 in 1" ?

**Comment by ergo720** [comment] 2017-08-21 17:30
It crashes on booting after displaying something.
win10, [0x9E115330], https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/c8c4f81e73041568da09be9958446168ed93a85b
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1239639/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1239641/KrnlDebug.txt)
![capture](https://user-images.githubusercontent.com/30000751/29531047-564d7914-8696-11e7-939f-953115d838b5.PNG)

**Comment by fatjohnny118** [comment] 2017-08-23 05:41
yes it was a 9 in 1 even though says unleash x so i dunno

**Comment by BenNottelling** [comment] 2017-08-31 22:29
Hmm, could it have been a 9 games in 1 type of thing?

**Comment by LukeUsher** [comment] 2017-09-01 05:01
It will be, but the fact it uses unleash X is evidence that it's not a real Microsoft release. In fact, by googling 9 in 1 for Xbox, the only real result I find is on a piracy site. 9-in-1 is definitely a pirated compilation of games.

**Comment by BenNottelling** [comment] 2017-09-01 05:25
So I vote to close this then

**Comment by LukeUsher** [comment] 2017-09-01 05:40
Agreed, if somebody wants to create a real issue for unleashx, by actually running the real unleash X they're welcome too, but piracy compilations will not be supported.

**Closed by LukeUsher** 2017-09-01 05:40 UTC
Labels: region-japan, region-other, region-us-canada, state-unverified, type-homebrew, xdk-4627

**Comment by ObiKKa** [comment] 2018-04-02 19:34
Hey, I came across this new video from Modern Vintage Gamer (The guy who also built/ported a few emulators for the OG Xbox back in the days). In it he shows you how to use a dashboard software, especially ones with a file manager window, to detect and unlock the hidden and/or unlockable games within a number of Xbox games! Thus you don't even have to play the relevant retail games themselves and bypass them entirely just to play these extra/hidden games! He recommended this software here, Unleash X, or XMBC, for example.

So, yeah, it'd be fun if these same methods can also be made to work on this CXBX-Reloaded software, as well as even XQEMU and OpenXBOX!

I have also created my own notepad (Also attached here) with further information such as which Xbox games and even some old movie DVDs (With demos that could be played on the OG Xbox) are known to have additional hidden/unlockable games. Yes, I have had to scroll through the very long user comments section in that video just to collect this information!
[Unlock-Hidden-Xbox-Games_With-Dashboard.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1869115/Unlock-Hidden-Xbox-Games_With-Dashboard.txt)

Enjoy viewing the video, everybody!
- [Hidden and Unlockable Games for The Original Xbox - Easily play with a modded Xbox | MVG](https://www.youtube.com/watch?v=UVojVDI52Jk) (Modern Vintage Gamer. Published on Mar 26, 2018.)

**Comment by LukeUsher** [comment] 2018-04-02 21:51
You can do this already for the most part: just select the unlockable games xbe rather than the main default.xbe.

**Comment by smallspud68** [comment] 2018-08-24 06:36
It's opening on hle, but all the text is really distorted.

I recorded it here, https://youtu.be/j7s1TeFXJXI

**Comment by Margen67** [comment] 2020-02-15 05:23
Duplicate of #382.
