### ISSUE TITLE
MechAssault2 [MS-107] [1.06]

### ISSUE THREAD

**Issue by T1T4N1UM013** [Cxbx-Reloaded/game-compatibility#1043] opened 2020-09-10 18:01 UTC
### Description

When I want to launch the game (Open default.xbe then Start Emulation), a crash sound is detected and a error popup is displayed after few second

![Sans titre](https://user-images.githubusercontent.com/71092644/92776569-ad3c9600-f39f-11ea-94b5-54cd9e20b847.png)
```

```

### Dumps

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/5203785/KrnlDebug.txt)

### Status
**Previous behavior:** 
None reported

**Current behavior:**
When I want to launch the game a crash sound is detected and a error popup is displayed

### Additional Information
W10, AMD Ryzen7, CG nvidia 960, 16Go ram
Cxbx-Reloaded
Version fa6387a (sep 8 2020)

**Comment by T1T4N1UM013** [comment] 2020-09-10 20:59
forgot include xbe.txt 
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/5204633/Xbe.txt)

**Comment by Margen67** [comment] 2020-09-10 21:19
Duplicate of #500

**Closed by Margen67** 2020-09-10 21:19 UTC
