### ISSUE TITLE
Deathrow [US-004] [1.03]

### ISSUE THREAD

**Issue by jiangwei4** [Cxbx-Reloaded/game-compatibility#1033] opened 2020-07-27 21:17 UTC
### Description

Unable to determine default xbox backbuffer

```
* Unable to determine default xbox backbuffer
```

### Dumps

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4984472/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4984474/KrnlDebug.txt)

### Status
**Previous behavior:** 

**Current behavior:**

Unable to determine default xbox backbuffer

### Screenshots

![image](https://user-images.githubusercontent.com/15106785/88592903-07d39a00-d05f-11ea-9532-92a998815c19.png)

### Additional Information

I dont have enable any hacks

**Comment by Margen67** [comment] 2020-07-28 02:42
Duplicate of #726

**Closed by Margen67** 2020-07-28 02:42 UTC
Labels: meta-duplicate
