### ISSUE TITLE
Carve [54540010]

### ISSUE THREAD

**Issue by kurayami6** [Cxbx-Reloaded/game-compatibility#362] opened 2017-09-14 20:01 UTC
https://en.wikipedia.org/wiki/Carve_(video_game)
### Description

Game only shows brief flashes of white before showing green and crashing

### Dumps 

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1304382/Xbe.txt)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1304383/KrnlDebug.txt)

### Status
**Previous behavior:**

**Current behavior:**

### Screenshots 

![capture](https://user-images.githubusercontent.com/31968468/30453134-30ed3530-99db-11e7-8fc6-4f692f92e1e1.PNG)

**Comment by CakeLancelot** [comment] 2017-09-14 23:01
Duplicate of #286. I've gone ahead and moved any relevant information there so this can be closed.

**Closed by CakeLancelot** 2017-09-14 23:01 UTC
