### ISSUE TITLE
DINO CRISIS 3 [CC-003] [1.04]

### ISSUE THREAD

**Issue by mohsinous** [Cxbx-Reloaded/game-compatibility#921] opened 2019-09-10 18:53 UTC
Description
Every things is OK till i choose Easy after selecting New Game!!! some time black screen, sometime stuck at Loading screen

Screenshots
![Cxbx-Reloaded f7f7aee8 (Sep 10 2019) _ Emulating CC-003 v1 04 (DINO CRISIS 3) 9_10_2019 11_21_14 PM](https://user-images.githubusercontent.com/32609205/64641651-d986a500-d421-11e9-82cc-251cda56c492.png)
![Cxbx-Reloaded f7f7aee8 (Sep 10 2019) _ Emulating CC-003 v1 04 (DINO CRISIS 3) 9_10_2019 11_21_25 PM](https://user-images.githubusercontent.com/32609205/64641656-dc819580-d421-11e9-809b-dae38559866a.png)
![Cxbx-Reloaded_fca123f8_Sep_10_2019___Emulating_CC-003_v1 04_DINO_CRISIS_3_9_10_2019_7_50_12_PM](https://user-images.githubusercontent.com/32609205/64641666-e0adb300-d421-11e9-8cee-1dad2898bc8c.png)

**Comment by mohsinous** [comment] 2019-09-10 19:18
found somethings funny!! when the loading screen is orange, game wont boot!!! (Resetting the game ...) but when its blue, it will boot!! (actually it is loading)
![Cxbx-Reloaded v0 1 (Jul 13 2018) _ Emulating CC-003 v1 04 (DINO CRISIS 3) 9_10_2019 11_45_04 PM](https://user-images.githubusercontent.com/32609205/64643389-83b3fc00-d425-11e9-8065-c70df8fbe793.png)

**Comment by mohsinous** [comment] 2019-09-10 19:19
the blue loading screen was captured from v0.1

**Comment by mohsinous** [comment] 2019-09-17 15:14
its lonely here ....
i am talking to myself

**Comment by ArslanBhatti** [comment] 2019-09-26 19:11
same issue here... you are not alone dear :(

**Comment by sarutobi47** [comment] 2020-01-28 03:51
help please I can not play dino crisis 3 always load in orange as in the graph above you can sometimes play but only for a short moment then stops

**Comment by sarutobi47** [comment] 2020-01-28 03:52
![dini](https://user-images.githubusercontent.com/60375493/73234364-1567a000-4160-11ea-8321-f58802b5e755.png)

**Comment by sarutobi47** [comment] 2020-01-28 03:52
please

**Comment by LuismaSP89** [comment] 2020-02-12 19:08
Same issue here with the latest development build, but only blackscreen, not the "now loading screen"

**Comment by ObiKKa** [comment] 2020-04-21 19:57
This issue is a duplicate of the old issue (link seen just above). Close this down?
Just copy-paste the title ID over there.

**Comment by Margen67** [comment] 2020-04-21 21:00
Duplicate of #114

**Closed by Margen67** 2020-04-21 21:00 UTC
Labels: duplicate
