### ISSUE TITLE
4x4 EVO 2 [54540001]

### ISSUE THREAD

**Issue by GeeseHoward** [Cxbx-Reloaded/game-compatibility#331] opened 2017-09-06 04:44 UTC
### Description

Game passes initial loading screen, then CXBX Reloaded crashes
![4x4](https://user-images.githubusercontent.com/31681252/30094808-e008aa84-9311-11e7-8e14-3d8e12afcd30.PNG)

### Status
**Previous behavior:**

**Current behavior:**

**Comment by BenNottelling** [comment] 2017-09-06 04:54
You are still missing dumps, also isn't there already an issue for this game? If there is you should be commenting on that rather than creating another issue

**Comment by literalmente-game** [comment] 2017-09-06 05:01
Duplicate of https://github.com/Cxbx-Reloaded/game-compatibility/issues/49

**Comment by CakeLancelot** [comment] 2017-09-06 05:21
Again, please search and make sure you aren't creating duplicates. Closing this one as well.

**Closed by CakeLancelot** 2017-09-06 05:21 UTC
