### ISSUE TITLE
Bloody Roar Extreme [48550001]

### ISSUE THREAD

**Issue by kurayami6** [Cxbx-Reloaded/game-compatibility#363] opened 2017-09-14 20:12 UTC
http://au.ign.com/games/bloody-roar-extreme

### Description

Crashes instantly with error message 

### Dumps 

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1304413/Xbe.txt)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1304414/KrnlDebug.txt)

### Status
**Previous behavior:**

**Current behavior:**

### Screenshots 

![capture](https://user-images.githubusercontent.com/31968468/30453593-b7294322-99dc-11e7-8e65-6fc678bfa67c.PNG)

### Additional Information

Xbox version doesn't have a dedicated wikipedia page, so I linked to an IGN article to prove the game exists.

**Comment by CakeLancelot** [comment] 2017-09-14 23:24
Duplicate of #271. I've gone ahead and transferred any relevant information, this will be closed.

**Closed by CakeLancelot** 2017-09-14 23:24 UTC
