### ISSUE TITLE
TaoFeng - Fist of the Lotus.

### ISSUE THREAD

**Issue by SonicThePS4** [Cxbx-Reloaded/game-compatibility#840] opened 2018-07-04 22:57 UTC
### Description

It's showing me this message.

```

```

### Dumps 
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2164474/Xbe.txt)

Sorry it won't let me dump the Kernel for some weird reason.

### Status
**Previous behavior:** 

**Current behavior:**

### Screenshots
![untitled](https://user-images.githubusercontent.com/39503785/42295780-e3ae12d6-7fbb-11e8-8a5c-d67c2721cb55.png)

**Comment by ergo720** [comment] 2018-07-05 10:35
Isn't this a duplicate of #602? The TitleId of that dump is 0x4D530014 -> "MS-020" which is the same as this one

**Comment by SonicThePS4** [comment] 2018-07-05 17:01
Ohh okay. But yeah it is.

**Closed** 2018-07-06 17:08 UTC
Labels: region-japan, region-other, region-us-canada, state-crashes, type-retail, xbe-tampered-with, xdk-5233
