### ISSUE TITLE
All-Star Baseball '04

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#222] opened 2017-08-28 08:43 UTC
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255695/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255696/KrnlDebug.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Voxel9** [comment] 2017-08-28 09:00
Duplicate of #21

**Closed** 2017-08-28 09:46 UTC
