### ISSUE TITLE
Amped

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#227] opened 2017-08-28 08:48 UTC
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255755/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255756/KrnlDebug.txt)
[PSDef000.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255757/PSDef000.txt)
[PSDef001.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255758/PSDef001.txt)
[PSDef002.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255759/PSDef002.txt)
[PSDef003.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255760/PSDef003.txt)
[PSDef004.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255761/PSDef004.txt)
[PSDef005.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255762/PSDef005.txt)
[PSDef006.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255763/PSDef006.txt)
[PSDef007.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255764/PSDef007.txt)
[PSDef008.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255765/PSDef008.txt)
[PSDef009.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255766/PSDef009.txt)
[PSDef010.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255767/PSDef010.txt)
[PSDef011.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255768/PSDef011.txt)
[PSDef012.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255769/PSDef012.txt)
[PSDef013.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255770/PSDef013.txt)
[PSDef014.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255771/PSDef014.txt)
[PSDef015.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255773/PSDef015.txt)
[PSDef016.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255772/PSDef016.txt)
[PSDef017.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255774/PSDef017.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Voxel9** [comment] 2017-08-28 08:58
Duplicate of #16

**Closed** 2017-08-28 09:45 UTC
