### ISSUE TITLE
AFL Premiership

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#215] opened 2017-08-28 08:29 UTC
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255597/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255599/KrnlDebug.txt)
[PSDef000.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255600/PSDef000.txt)
[PSDef001.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255601/PSDef001.txt)
[PSDef002.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255602/PSDef002.txt)
[PSDef003.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255604/PSDef003.txt)
[PSDef004.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255605/PSDef004.txt)
[PSDef005.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255603/PSDef005.txt)
[PSDef006.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255606/PSDef006.txt)
[PSDef007.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255607/PSDef007.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Voxel9** [comment] 2017-08-28 09:27
Duplicate of #27

**Comment by BenNottelling** [comment] 2017-08-28 09:32
Comment on #27 now

**Closed** 2017-08-28 09:32 UTC
