### ISSUE TITLE
Dino Crisis 3 [43430003]

### ISSUE THREAD

**Issue by kurayami6** [Cxbx-Reloaded/game-compatibility#355] opened 2017-09-14 18:17 UTC
https://en.wikipedia.org/wiki/Dino_Crisis_3
### Description

Game renders perfectly, and gets to the last loading screen before gameplay, just incredibly fast. Too fast to even take screenshots

### Dumps 

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1304033/Xbe.txt)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1304034/KrnlDebug.txt)

### Status
**Previous behavior:**

**Current behavior:**

### Screenshots 

![capture](https://user-images.githubusercontent.com/31968468/30446487-ad6d8092-99cc-11e7-9f2c-94cf65279042.PNG)

**Comment by hotzenplotz3000** [comment] 2017-09-14 20:23
duplicate of #114

**Comment by kurayami6** [comment] 2017-09-14 20:26
I searched for it and nothing came up. Sorry.

**Comment by CakeLancelot** [comment] 2017-09-14 23:28
I've moved this post to #114 with some tweaks. Closing this one.

**Closed by CakeLancelot** 2017-09-14 23:28 UTC
