### ISSUE TITLE
Batman Dark Tomorrow

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#412] opened 2017-10-13 07:04 UTC
### Description

```

```

### Status
**Previous behavior:** 
None reported

**Current behavior:**
Goes in-game (when using master)
Shows near-perfect menu (when using PatrickvL\WIPLessVertexPatching)

### Screenshots 
![Batman Loading](https://media.discordapp.net/attachments/293096509019258880/367352437830582276/bat.png)
![Batman Dark Tomorrow menu](https://media.discordapp.net/attachments/293096509019258880/367215713045315586/Cxbx_2017-10-10_04-34-37-32.png)

### Additional Information
Tested with https://github.com/PatrickvL/Cxbx-Reloaded/commit/87dd49cde89be7611571c9c71498327ab97129d2
This branch is not yet merged into Cxbx-Reloaded master branch.

**Comment by CakeLancelot** [comment] 2017-10-13 08:25
There's already an issue for this title (#394), do you want me to combine the two or leave them separate?

**Comment by PatrickvL** [comment] 2017-10-13 08:28
Oops, please combine them then. Thanks!

**Comment by CakeLancelot** [comment] 2017-10-13 08:36
> Oops, please combine them then. Thanks!

Done, closing as this one then.
Duplicate of #394

**Closed by CakeLancelot** 2017-10-13 08:36 UTC
Labels: state-partially-working, type-retail, xbe-dump-needed
