### ISSUE TITLE
American Chopper 2 Full Throttle

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#223] opened 2017-08-28 08:45 UTC
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255699/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255700/KrnlDebug.txt)
[PSDef000.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255701/PSDef000.txt)
[PSDef001.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255702/PSDef001.txt)
[PSDef002.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255704/PSDef002.txt)
[PSDef003.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255703/PSDef003.txt)
[PSDef004.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255705/PSDef004.txt)
[PSDef005.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255706/PSDef005.txt)
[PSDef006.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255707/PSDef006.txt)
[PSDef007.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255708/PSDef007.txt)
[PSDef008.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255709/PSDef008.txt)
[PSDef009.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255710/PSDef009.txt)
[PSDef010.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255711/PSDef010.txt)
[PSDef011.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255712/PSDef011.txt)
[PSDef012.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255713/PSDef012.txt)
[PSDef013.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255714/PSDef013.txt)
[PSDef014.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255715/PSDef014.txt)
[PSDef015.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255716/PSDef015.txt)
[PSDef016.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255717/PSDef016.txt)
[PSDef017.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255718/PSDef017.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Voxel9** [comment] 2017-08-28 09:21
Duplicate of #20

**Closed** 2017-08-28 09:47 UTC
