### ISSUE TITLE
Fuzion Frenzy [4D530002]

### ISSUE THREAD

**Issue by ZachSaucier** [Cxbx-Reloaded/game-compatibility#443] opened 2017-11-27 10:16 UTC
### Description
[Fuzion Frenzy](https://en.wikipedia.org/wiki/Fuzion_Frenzy) can be "opened" using Cxbx but when it is told to "Start" (Emulation -> Start), it takes some time then exits with the below error.

```
Received Exception Code 0xC0000005 @ EIP := 0x04059175
```

### Dumps 

XBE Dump:
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1505454/Xbe.txt)

KrnlDebug:
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1505457/KrnlDebug.txt)

HLE Cache:
https://ufile.io/g4l55 (off site because GitHub doesn't support uploading .ini formats; let me know if you'd like me to use a different site)

### Status
**Previous behavior:** 
None reported.

**Current behavior:**
Exits on start due to an error. 

### Screenshots 
None necessary.

**Comment by jackchentwkh** [comment] 2017-11-27 10:20
instead of posting the xbe dump and log text, could you please simply attach the dump file and log files?
that would be easier for the developer the collect and analyze the data.

**Comment by ZachSaucier** [comment] 2017-11-27 10:25
Sure. Sorry about that.

**Comment by BenNottelling** [comment] 2017-11-28 05:04
@ZachSaucier Sorry I left out instructions on the HLE cache. I've updated the template to show you how. Just for convenience, here it is.  

> To upload the HLE cache open up command prompt and the following,
start C:\Users\%username%\AppData\Roaming\Cxbx-Reloaded\HLECache
Here you will now see all of the HLE Cache's created by Cxbx Reloaded. Find the one with the title of the game you are creating an issue on and then you can 1: rename it to a .txt or 2: compress it to a .zip
Then drag and upload the .zip/.txt to the issue you are creating.

**Comment by PatrickvL** [comment] 2017-11-28 06:42
%appdata%/Cxbx-Reloaded is much shorter

**Comment by BenNottelling** [comment] 2017-11-28 06:53
I actually didn't know you could do that 😂. Thinking about it now though that actually makes sense. I'll make note of that haha thanks!

**Comment by ZachSaucier** [comment] 2017-11-28 13:26
I added the HLE cache and linked it in the post above.

**Comment by CakeLancelot** [comment] 2018-01-27 20:34
Duplicate of #598, closing this one as the aforementioned has more up to date information.

**Closed by CakeLancelot** 2018-01-27 20:34 UTC
Labels: region-japan, region-other, region-us-canada, state-crashes, type-retail, xbe-tampered-with, xdk-3911, xdk-3925
