### ISSUE TITLE
NBA Live 2002 [EA-003]

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/game-compatibility#828] opened 2018-06-25 16:17 UTC
### Description

Booting, interactive - you can navigate in menus, but crashing after match loading, sound is missing.

```
Received Exception Code 0xC0000005 @ EIP := 0x6241C5A1
```

### Dumps 

[KrnlDebug_nba2002.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2133866/KrnlDebug_nba2002.txt)
[Xbe_nba2002.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2133867/Xbe_nba2002.txt)

### Status
**Previous behavior:** 

None reported
**Current behavior:**

Interactive, crashing after match loading.

### Screenshots

![image](https://user-images.githubusercontent.com/24764335/41862108-b27c3f06-78ab-11e8-8992-808ffe679416.png)
![image](https://user-images.githubusercontent.com/24764335/41862151-c4ef1b18-78ab-11e8-9ebf-6231418e7c97.png)

**Comment by Voxel9** [comment] 2018-06-25 16:20
Duplicate of #103. Transferring info from this issue to there.

**Closed by Voxel9** 2018-06-25 16:20 UTC
