### ISSUE TITLE
25 TO LIFE

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#208] opened 2017-08-28 08:20 UTC
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255511/KrnlDebug.txt)
[PSDef000.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255512/PSDef000.txt)
[PSDef001.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255514/PSDef001.txt)
[PSDef002.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255513/PSDef002.txt)
[PSDef003.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255515/PSDef003.txt)
[PSDef004.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255516/PSDef004.txt)
[PSDef005.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255517/PSDef005.txt)
[PSDef006.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255518/PSDef006.txt)
[PSDef007.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255519/PSDef007.txt)
[PSDef008.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255520/PSDef008.txt)
[PSDef009.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255521/PSDef009.txt)
[PSDef010.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255522/PSDef010.txt)
[PSDef011.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255523/PSDef011.txt)
[PSDef012.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255524/PSDef012.txt)
[PSDef013.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255525/PSDef013.txt)
[PSDef014.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255526/PSDef014.txt)
[PSDef015.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255527/PSDef015.txt)
[PSDef016.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255528/PSDef016.txt)
[PSDef017.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255529/PSDef017.txt)
[PSDef018.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255530/PSDef018.txt)
[PSDef019.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255531/PSDef019.txt)
[PSDef020.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255532/PSDef020.txt)
[PSDef021.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255533/PSDef021.txt)
[PSDef022.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255534/PSDef022.txt)
[PSDef023.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255535/PSDef023.txt)
[PSDef024.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255536/PSDef024.txt)
[PSDef025.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255537/PSDef025.txt)
[PSDef026.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255538/PSDef026.txt)
[PSDef027.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255539/PSDef027.txt)
[PSDef028.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255540/PSDef028.txt)
[PSDef029.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255541/PSDef029.txt)
[PSDef030.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255542/PSDef030.txt)
[PSDef031.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255543/PSDef031.txt)
[PSDef032.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255544/PSDef032.txt)
[PSDef033.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255545/PSDef033.txt)
[PSDef034.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255546/PSDef034.txt)
[PSDef035.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255547/PSDef035.txt)
[PSDef036.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255548/PSDef036.txt)
[PSDef037.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255549/PSDef037.txt)
[PSDef038.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255550/PSDef038.txt)
[PSDef039.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255551/PSDef039.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Voxel9** [comment] 2017-08-28 09:50
Duplicate of #38

**Closed by Voxel9** 2017-08-28 09:50 UTC
