### ISSUE TITLE
Roller Coaster Tycoon [IG-046] [v1.05]

### ISSUE THREAD

**Issue by bryce13950** [Cxbx-Reloaded/game-compatibility#993] opened 2020-05-24 21:33 UTC
### Description

WOOOOOOOOOOOOO!!!!!! This game works nearly perfectly. The only issue that was found while testing was missing background music from the rides such as the merry go round, and the soundtrack on the title screen.

### Dumps

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4674445/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4674446/KrnlDebug.txt)

### Status
**Previous behavior:** 

**Current behavior:**

Almost perfect, missing an audio track.

### Screenshots

![ingame](https://user-images.githubusercontent.com/6487928/82765405-03002900-9e17-11ea-8f21-080d5f98da97.PNG)

**Comment by Margen67** [comment] 2020-05-25 04:00
Potential duplicate of #472.

**Comment by gandalfthewhite19890404** [comment] 2020-05-25 05:02
Xbe.txt from mechassault2, check it, please,

**Comment by bryce13950** [comment] 2020-06-14 19:17
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4777058/Xbe.txt)

My mistake on the incorrect xbe file. Here is the proper one.

**Comment by Margen67** [comment] 2020-06-16 23:02
Duplicate of #472 (based on xbe region)

**Closed by Margen67** 2020-06-16 23:02 UTC
Labels: issue-audio, potential-duplicate, state-working, xdk-5233
