### ISSUE TITLE
NamcoMuseum [Namco Museum] [NM-007] [1.01]

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#176] opened 2017-08-21 15:29 UTC
## Issues
 - Loses sound at main menu and graphical glitches at menu

_From @bhodg22 on March 24, 2017 1:24_

Game loses sound once you reach the main menu and has some graphical glitches but apart from that very playable
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/866619/KrnlDebug.txt)
![menu](https://cloud.githubusercontent.com/assets/5080749/24276730/75f9b274-1084-11e7-995b-9545a253cd52.png)
![gameplay](https://cloud.githubusercontent.com/assets/5080749/24276733/7a531c52-1084-11e7-8d46-e618e3e41bc1.png)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#265_

**Comment by PatrickvL** [comment] 2017-08-21 15:29
_From @LukeUsher on March 24, 2017 6:13_

That's great. I've tested this game many times over the past year and it's never worked. This is a good sign we are making progress!

**Comment by PatrickvL** [comment] 2017-08-21 15:29
_From @bhodg22 on March 25, 2017 9:0_

After some more testing I did find that Namco museum will crash back to the cxbx screen on certain games
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/869872/KrnlDebug.txt)
 
I also noticed that this game gets a significant speed boost to pretty much full speed when I have dota 2 open in the background, when I close dota again the game goes back to about 50% speed

**Comment by PatrickvL** [comment] 2017-08-21 15:29
_From @ObiKKa on April 18, 2017 17:19_

After PR #375 (Simple overlay conversion & others) and #376 (Integrated copy OOVPAs), unfortunately, the video previews look like a horror show!
Reply to below: Yes, Turok did run OK in Hardware Video mode that I tested (Will work fine in normal mode too). Also Namco's 50th Anniversary pack somehow doesn't work. But with the POC 0.0.1 release last year or some builds this year it showed a grainy snap of a list of games if I pressed on a crash message button but I can't remember. I think that was with a secondary xbe file and not the default.xbe file.

![collage-2017-04-19](https://cloud.githubusercontent.com/assets/18428108/25143739/e55d21f8-24ae-11e7-8f26-6d34a21fb08f.png)
[KrnlDebug_(2017-04-19).txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/930520/KrnlDebug_.2017-04-19.txt)

**Comment by PatrickvL** [comment] 2017-08-21 15:29
I really should get a copy of this game, so that I can make sure it actually works before I submit another problematic commit like this. My apologies - I meant it well, Turok ran okay, I figured other video plays would work too...

**Comment by PatrickvL** [comment] 2017-08-21 15:29
_From @ObiKKa on May 2, 2017 16:49_

Oh no, these error messages are spreading like wildfire, interrupting several games before they can even play a movie or get to a menu properly!

![2017-may-03 _error-box_01](https://cloud.githubusercontent.com/assets/18428108/25628854/0c0abe4e-2fab-11e7-801d-a2c6e4d7d5e3.png)

**Comment by PatrickvL** [comment] 2017-08-21 15:29
_From @bhodg22 on May 13, 2017 3:1_

I also have the same regression

**Comment by CakeLancelot** [comment] 2017-09-16 17:54
Marked this as unverified as a regression has not been tested for since May. If someone could test on the latest build I will update the game's state.

**Comment by Voxel9** [comment] 2017-09-17 13:37
Ask and ye shall receive.

---
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1309110/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1309111/Xbe.txt)

---
Now, it seems that it displays the Namco logo, and then just crashes immediately after. So yeah, I think there has been some regression since May time...

---
![capture2](https://user-images.githubusercontent.com/16278868/30521296-50d4b388-9bb5-11e7-9c32-08efe1adad60.PNG)
![capture3](https://user-images.githubusercontent.com/16278868/30521297-50d7677c-9bb5-11e7-92bb-c0652850a7a6.PNG)

**Comment by RadWolfie** [comment] 2017-09-17 14:30
Can you try again by adding `XGetDeviceChanges=5f9023` to your HLE cache file? I think this is the cause of crash.

**Comment by Voxel9** [comment] 2017-09-17 14:33
There already appears to be an `XGetDeviceChanges=5f9023` in my cache file already

![image](https://user-images.githubusercontent.com/16278868/30521812-86ef88e6-9bbd-11e7-9d3d-1cd1ea679c59.png)

**Comment by RadWolfie** [comment] 2017-09-17 14:34
Oops, I meant without XGetDeviceChanges from your HLE cache file.

**Comment by Voxel9** [comment] 2017-09-17 14:38
Unfortunately it didn't change the behaviour at all 😕

**Comment by RadWolfie** [comment] 2017-09-17 14:40
Alright, thanks for trying. I wonder if the issue somewhere internally Cxbx is the cause.

**Comment by bhodg22** [comment] 2018-03-24 12:33
As of the latest commits https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/52e289252e71580e53020d0483c7c47afb31862b, this now goes back to main menu and plays sound and videos correctly!
![image](https://user-images.githubusercontent.com/5080749/37863962-10d02d7a-2fb3-11e8-97ac-e496d3ff2195.png)

You can also select each of the games (such as pacman and galaga) but only a black screen is shown, however audio from the game can still be heard

**Comment by bhodg22** [comment] 2018-06-09 12:51
This game seems to be 100% now, can't find any issues with audio or with the games
![image](https://user-images.githubusercontent.com/5080749/41191772-82dba6ea-6c37-11e8-8a42-38572da12cd9.png)
![image](https://user-images.githubusercontent.com/5080749/41191773-8677fab0-6c37-11e8-8dc0-dee595f9598a.png)
![image](https://user-images.githubusercontent.com/5080749/41191774-8a340cc0-6c37-11e8-83c1-4ba93617343c.png)

**Comment by Margen67** [comment] 2020-06-27 06:49
Duplicate of #68

**Closed by Margen67** 2020-06-27 06:49 UTC
Labels: meta-duplicate
