### ISSUE TITLE
AFL Live Premiership Edition

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#214] opened 2017-08-28 08:28 UTC
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255585/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255586/KrnlDebug.txt)
[PSDef000.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255588/PSDef000.txt)
[PSDef001.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255590/PSDef001.txt)
[PSDef002.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255594/PSDef002.txt)
[PSDef003.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255591/PSDef003.txt)
[PSDef004.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255592/PSDef004.txt)
[PSDef005.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255593/PSDef005.txt)
[PSDef006.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255589/PSDef006.txt)
[PSDef007.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255595/PSDef007.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Voxel9** [comment] 2017-08-28 09:26
Duplicate of #28

**Comment by BenNottelling** [comment] 2017-08-28 09:31
Commented #28

**Closed** 2017-08-28 09:31 UTC
