### ISSUE TITLE
State of Emergency

### ISSUE THREAD

**Issue by ddraigcymraeg** [Cxbx-Reloaded/game-compatibility#932] opened 2020-01-01 06:52 UTC
Description:
See image pasted below. Game goes through main menu fine, but game rendering does not work....main menu overlay doesnt go away, sometimes completely covering the game, othertimes partly, like in the picture, making the game unplayable. This was on the latest dev build of cxbx reloaded downloaded today. First time attempting to run the game with any version of cxbx.

![image](https://user-images.githubusercontent.com/17283820/71638836-cb5ecd80-2c38-11ea-8f15-e65dbbdb3f03.png)

**Comment by CakeLancelot** [comment] 2020-01-01 07:37
Might be a duplicate of #334, unless this is a different game region/version. Please upload an Xbe dump so we can check this and better categorize it.

To upload an Xbe dump:

1. Open an Xbe file
2. Go to Edit > Dump Xbe Info To... >File...
3. Save the file to a location of your choice
4. Upload to Github by dragging and dropping

**Comment by ddraigcymraeg** [comment] 2020-01-01 17:20
Attached below. I checked out #334, I dont get an error message or apparent crash, the game seems playable,  but the rendering is off.
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4014311/Xbe.txt)

**Comment by f15242** [comment] 2020-01-02 19:03
indirme linki

**Comment by Margen67** [comment] 2020-06-16 15:05
Duplicate of #334

**Closed by Margen67** 2020-06-16 15:05 UTC
Labels: meta-duplicate, meta-invalid
