### ISSUE TITLE
Half-Life 2

### ISSUE THREAD

**Issue by 13yearoldADULT** [Cxbx-Reloaded/game-compatibility#417] opened 2017-10-19 18:50 UTC
## Issues
-  Black Screen (images working)

As you start the game emulating the valve theme starts up and you get a black screen upon loading the 
game
![screenshot_2017-10-19-21-42-10](https://user-images.githubusercontent.com/32934452/31788235-d400a1fc-b516-11e7-9404-13e370a4ed5b.png)
After the song fades you will be granted with an old 2002 early source logo
![screenshot_2017-10-19-21-42-22](https://user-images.githubusercontent.com/32934452/31788286-f9d7ea16-b516-11e7-9c5c-72859cf067cd.png)
After the normal hl2 copyright term splash comes in
![screenshot_2017-10-19-21-42-33](https://user-images.githubusercontent.com/32934452/31788345-19626988-b517-11e7-9e10-6146778c139a.png)
And you will get the black screen back but the sounds still work. Only controls menu works giving you a helpful image
![screenshot_2017-10-19-21-42-47](https://user-images.githubusercontent.com/32934452/31788418-48676936-b517-11e7-88d8-1faed166622f.png)
But going in the chapters will cause the game to crash

Perhaps the burned BIK file loader is missing and the gpu drawer and render missing. Can you fix it to work properly?

**Comment by 13yearoldADULT** [comment] 2017-10-19 18:51
By saying 2002 its an actual 2002 source logo which has been used to make the game work

**Comment by CakeLancelot** [comment] 2017-10-20 01:20
I believe that this is a game that has a launcher xbe (which appears to be somewhat working), as well as a LTCG game xbe. The game portion will require some more LLE work before it can go in game.

Also, the template is there for a reason. Please use it or at least provide all the information. (Logs, Xbe dumps, etc.)

**Comment by CakeLancelot** [comment] 2018-01-13 06:37
Duplicate of #538

**Closed by CakeLancelot** 2018-01-13 06:37 UTC
Labels: issue-video, state-interactive, type-retail, xbe-dump-needed
