### ISSUE TITLE
9 IN 1

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#207] opened 2017-08-28 08:19 UTC
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258075/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255502/KrnlDebug.txt)
[PSDef000.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255503/PSDef000.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255504/CxbxDebug.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by ergo720** [comment] 2017-08-28 10:17
This is very likely a duplicate of #35

**Comment by ergo720** [comment] 2017-08-28 21:30
Ok, this is UnleashX, so it's a duplicate

**Comment by LukeUsher** [comment] 2017-08-29 06:25
Ergo720 is right. UnleashX is an unofficial dashboard often used as a launcher in homebrew (and also pirated) compilations of games. Closing

**Closed by LukeUsher** 2017-08-29 06:25 UTC
