### ISSUE TITLE
ThousandLand

### ISSUE THREAD

**Issue by Shibusken** [Cxbx-Reloaded/game-compatibility#893] opened 2019-05-03 13:37 UTC
### Description
The "start" works until the initial screen.
In the "new game" screen no command works
Obs: performed with two different game files (each coming from different sources).

### Dumps 

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/3142044/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/3142045/Xbe.txt)

[Xbe2.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/3142098/Xbe2.txt)
[KrnlDebug2.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/3142096/KrnlDebug2.txt)

### Status
**Previous behavior:** 

None reported

**Current behavior:**

In the "new game" screen no command works

### Screenshots
![ThousandLand](https://user-images.githubusercontent.com/43501076/57140866-2fba4c00-6d8f-11e9-8193-56c96ea71f37.png)

### Additional Information
Tested with 4986023e (May 1 2019)

**Comment by CakeLancelot** [comment] 2019-05-03 16:33
Duplicate of #759

**Closed by CakeLancelot** 2019-05-03 16:33 UTC
