### ISSUE TITLE
Project Gotham Racing

### ISSUE THREAD

**Issue by SonicThePS4** [Cxbx-Reloaded/game-compatibility#779] opened 2018-05-25 14:54 UTC
### Description
Excellent Intro, But it goes in the black screen when it tries to go to the "Press Start Button" screen.

```

```

### Dumps 
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2039785/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2039808/KrnlDebug.txt)

### Status
**Previous behavior:** 

**Current behavior:**

### Screenshots

![untitled](https://user-images.githubusercontent.com/39503785/40550694-d914d1ca-6008-11e8-8285-cc8fa0d2a2f0.png)
![untitled](https://user-images.githubusercontent.com/39503785/40550976-b07e6586-6009-11e8-8109-3e07f6b6bc65.png)

**Comment by Voxel9** [comment] 2018-05-25 15:14
Closing as duplicate of #108. Above info has been transferred to that issue.

**Closed** 2018-05-25 15:17 UTC
