### ISSUE TITLE
Futurama [56550008]

### ISSUE THREAD

**Issue by kurayami6** [Cxbx-Reloaded/game-compatibility#359] opened 2017-09-14 18:46 UTC
https://en.wikipedia.org/wiki/Futurama_(video_game)

### Description

crashes on the first loading screen

### Dumps 

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1304131/Xbe.txt)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1304132/KrnlDebug.txt)

### Status
**Previous behavior:**

**Current behavior:**

### Screenshots 

![futurama](https://user-images.githubusercontent.com/31968468/30447952-c1525fac-99d0-11e7-8623-5f44ca1c04cc.PNG)

**Comment by hotzenplotz3000** [comment] 2017-09-14 19:21
duplicate of this issue #71

**Closed** 2017-09-14 20:08 UTC
