### ISSUE TITLE
Tom Clancy's Ghost Recon 2 [55530005]

### ISSUE THREAD

**Issue by dudefrom531** [Cxbx-Reloaded/game-compatibility#689] opened 2018-03-04 08:27 UTC
### Description

The game boots into the main menu, without showing main menu selections. Continuing to press A will boot into the game, but will crash with the error. Only the top left diagonal is shown, and speed is very inconsistent, glitchy, and fast in the main menu.

```
---------------------------
Cxbx-Reloaded
---------------------------
Received Exception Code 0xC0000005 @ EIP := 0x04070CF3

  Press "OK" to terminate emulation.
  Press "Cancel" to debug.
---------------------------
OK   Cancel   
---------------------------

```

### Dumps 

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1779729/KrnlDebug.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1779730/Xbe.txt)

### Status
**Previous behavior:** 

The game just crashed with the error located here: https://github.com/Cxbx-Reloaded/game-compatibility/issues/337

**Current behavior:**

Boots into main menu without showing main menu selection reel, glitchy speed, crashes when pressing A to get into game

### Screenshots 
https://i.imgur.com/lL4U0BC.png
https://i.imgur.com/RwwUhXM.png
https://i.imgur.com/jjoi6R8.png

**Comment by dudefrom531** [comment] 2018-03-04 08:29
How do I add labels, and I'm unsure of which labels to use too

**Comment by CakeLancelot** [comment] 2018-03-04 08:35
> How do I add labels, and I'm unsure of which labels to use too

Only issue maintainers can assign labels, in order for me (or other maintainers) to know which labels to apply we need an xbe dump, you should also include a KrnlDebug log so the developers can look into the cause of an error.

To upload an Xbe dump:

1. Open an Xbe file
2. Go to Edit > Dump Xbe Info To... >File...
3. Save the file to a location of your choice
4. Upload to Github by dragging and dropping

To create a log:

1. Go to View > Debug Output (Kernel) > File...
2. Choose where to save the log
3. Play the game until you encounter a crash
4. Repeat step 1 to turn off logging
5. Upload to Github via drag and drop

**Comment by CakeLancelot** [comment] 2018-03-04 08:37
Also, if this has no difference between #337 (differences in say region, or game edition/revision) you can post your findings there instead.

**Comment by dudefrom531** [comment] 2018-03-05 06:30
Added dumps

**Comment by CakeLancelot** [comment] 2018-03-05 07:05
This appears to be the same Xbe as #337 (except this one is tampered with..). I'm going to move everything over and close this one as a duplicate.

**Closed by CakeLancelot** 2018-03-05 07:05 UTC
Labels: issue-timing, region-japan, region-other, region-us-canada, state-interactive, type-retail, xdk-5849
