### ISSUE TITLE
AFL LIVE 2003

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#212] opened 2017-08-28 08:24 UTC
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255572/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255573/KrnlDebug.txt)
[PSDef000.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255574/PSDef000.txt)
[PSDef001.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255575/PSDef001.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Voxel9** [comment] 2017-08-28 09:26
Duplicate of #30

**Comment by BenNottelling** [comment] 2017-08-28 09:28
Copied as comment to #30

**Closed** 2017-08-28 09:28 UTC
