### ISSUE TITLE
Jet Set Radio Future issues

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#44] opened 2017-08-15 11:10 UTC
_From @HyperScorpio on August 6, 2017 19:26_

Funny how we spray in the cops back and it doesn´t bug the map at all. The save game graffiti appears a annoying white X in the middle and it hide you from the screen.

The game just crash on all Spray edit options and in the secound tutorial from Roboy Charather. 

A error as well when we go to a new stage.
We press ok and we able to play it.

![1](https://user-images.githubusercontent.com/30736913/28988980-77b27eee-796a-11e7-9007-2ac8308dae3b.png)

I can confirm in a few graffiti's they are fixed in the first map, but in the wrong position, instead having the normal one's, it shows others. 
Example: The Fish instead that red boy with a microfone.
And those one's are locked by the graffiti souls yet. :)
Check and test the original game first. 

PS: I remove the message before and put it as new issue for @RadWolfie recieve my message. :)

NEW.

In the end of the 2nd level when i paint the last graffiti the game stops and say the disc is dirty or damage.

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#619_

**Comment by PatrickvL** [comment] 2017-08-15 11:10
_From @JackaJacka123 on August 7, 2017 19:8_

This sounds a lot like issues found in #251 and/or #466

**Comment by PatrickvL** [comment] 2017-08-15 11:10
_From @RadWolfie on August 8, 2017 0:53_

I already made a record about this pop up message in issue #485, which is...

> EmuPatch_IDirectSound_SetOrientation return 0x80070057 (DSERR_INVALIDPARAM)


P.S. What you did not include per pop up message requested are function name and return value code. If it is different from this, then put it in the issue I mentioned above. Don't create a new issue just for this. Thanks.

**Comment by PatrickvL** [comment] 2017-08-15 11:10
_From @Sarkie on August 8, 2017 7:50_

Regarding graffiti.

Are you saying instead of one texture being there an incorrect one is loaded instead?

**Comment by PatrickvL** [comment] 2017-08-15 11:10
_From @HyperScorpio on August 8, 2017 11:33_

@Sarkie Yes. Or i'm wrong.

**Comment by PatrickvL** [comment] 2017-08-15 11:10
_From @Sarkie on August 8, 2017 13:18_

Can you verify on hardware if possible?

**Comment by PatrickvL** [comment] 2017-08-15 11:10
_From @CakeLancelot on August 8, 2017 18:8_

> Can you verify on hardware if possible?

I can confirm this issue (Second image is actual xbox):
![cxbx_2017-08-08_13-07-07](https://user-images.githubusercontent.com/5341136/29087166-a80c9e8a-7c3a-11e7-86ca-112b1dee72c8.png)
![graffiti](https://user-images.githubusercontent.com/5341136/29087180-adc70f86-7c3a-11e7-966d-2e9c78864814.png)

**Comment by PatrickvL** [comment] 2017-08-15 11:10
_From @HyperScorpio on August 8, 2017 18:37_

Even the font letters "Boost Dash" & "B button" are yellow and not white. Nice.

**Comment by PatrickvL** [comment] 2017-08-15 11:10
_From @ladsoftware on August 9, 2017 2:50_

 Cant wait to see everything working.

**Comment by PatrickvL** [comment] 2017-08-15 11:10
_From @Sarkie on August 9, 2017 8:51_

@CakeLancelot Do you have another example please? 

I am guessing/hoping it is loading the wrong textures in a specific way, e.g. off-by-one error 
I'm hoping its a similar bug to one of my fave Dolphin bugs.
https://github.com/dolphin-emu/dolphin/commit/ed67d1ae2f9693ed42867a2e79b7cae4427574e3

**Comment by PatrickvL** [comment] 2017-08-15 11:10
Wrong textures might be caused by an incorrect state after handling point sprite effects (as these move textures from stage 3 to 1). Or it might be mipmap related. We'll have to do some thorough investigation for this

**Comment by PatrickvL** [comment] 2017-08-15 11:10
_From @HyperScorpio on August 10, 2017 14:14_

Map Zone - 99th Street.

![3](https://user-images.githubusercontent.com/30736913/29174484-61736bca-7dde-11e7-8469-fb01e892a069.png)

Graffiti problems.
![2](https://user-images.githubusercontent.com/30736913/29174487-65b60314-7dde-11e7-9949-df0ee7488ce2.png)

The annoying white cross.
![1](https://user-images.githubusercontent.com/30736913/29174491-67f5a18e-7dde-11e7-8e46-346cf615842a.png)

The annoying brown rectangle.
![4](https://user-images.githubusercontent.com/30736913/29174495-6ae009f2-7dde-11e7-9dea-699c8afd5dad.png)

After beat the crazy cop.
![5](https://user-images.githubusercontent.com/30736913/29174498-6cd30368-7dde-11e7-9641-7e07a1997fe2.png)

Before entering on the Garage.
![6](https://user-images.githubusercontent.com/30736913/29174501-6f04f614-7dde-11e7-929a-13cce6ca2f8c.png)

**Comment by HyperScorpio** [comment] 2017-08-15 12:43
![1](https://user-images.githubusercontent.com/30736913/29316347-91c6b23e-81bf-11e7-966c-ebaa44b7f880.png)

This level is hard to bypass because is not many white things in front of you. 😢

**Comment by HyperScorpio** [comment] 2017-08-18 19:04
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1235369/Xbe.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1235370/CxbxDebug.txt)

[default.zip](https://github.com/Cxbx-Reloaded/game-compatibility/files/1235371/default.zip)

Everything from that level.

**Comment by HyperScorpio** [comment] 2017-08-21 16:31
I'm now in the last level. A lot of crashes but after a few saves we can bypass.

**Comment by CakeLancelot** [comment] 2017-09-16 18:39
Duplicate of #178

**Closed by CakeLancelot** 2017-09-16 18:39 UTC
Labels: type-retail

**Comment by HyperScorpio** [comment] 2017-09-17 00:55
Dont forget to post this last issue in tot the #178
