### ISSUE TITLE
Shrek [544d0001] various CreateHostResource errors

### ISSUE THREAD

**Issue by ESPPIRAL** [Cxbx-Reloaded/game-compatibility#717] opened 2018-04-15 11:50 UTC
Shrek shows this test-case: CreateHostResource : dwWidth < dwMinSize
In CreateHostResource (c:\projects\cxbx-reloaded\src\cxbxkrnl\emud3d8.cpp line 4307)

![bandicam 2018-04-15 13-43-12-777](https://user-images.githubusercontent.com/29869781/38778062-2829e310-40b3-11e8-8ec0-bc97df911bec.png)
![bandicam 2018-04-15 13-43-08-390](https://user-images.githubusercontent.com/29869781/38778063-292cf676-40b3-11e8-91c3-f723dda87e01.png)
![bandicam 2018-04-15 13-43-02-023](https://user-images.githubusercontent.com/29869781/38778064-2a3e2dfa-40b3-11e8-84af-cbd78ea565e8.png)
[shrekKrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1912347/shrekKrnlDebug.txt)

Game looks like this 

![bandicam 2018-04-15 13-42-12-701](https://user-images.githubusercontent.com/29869781/38778093-aa8f88aa-40b3-11e8-9de3-a15802d49fd8.png)
![bandicam 2018-04-15 13-42-24-150](https://user-images.githubusercontent.com/29869781/38778094-adc3ae52-40b3-11e8-8235-6e2c79d28d9d.png)

It's current status is ingame.

**Comment by Voxel9** [comment] 2018-04-15 13:14
Closing as duplicate of #663; merging this issue into that one.

**Closed by Voxel9** 2018-04-15 13:14 UTC

**Comment by PatrickvL** [comment] 2018-04-15 13:30
Thanks Voxel9 (and you too of course, ESPPIRAL)
