### ISSUE TITLE
Blinx: The time sweeper. Problems with vertex buffer

### ISSUE THREAD

**Issue by IsaabBoy** [Cxbx-Reloaded/game-compatibility#963] opened 2020-05-12 17:48 UTC
### Description

Stopped to appear the message, now it says 'failed to create vertex buffer'

### Screenshots

![Cxbx-Reloaded 12_05_2020 11_31_41 a  m](https://user-images.githubusercontent.com/65247566/81727533-bb5cc300-944e-11ea-9b22-b32010c7e5bf.png)
![Cxbx-Reloaded 12_05_2020 11_31_15 a  m](https://user-images.githubusercontent.com/65247566/81727535-bbf55980-944e-11ea-9387-3245796c0a60.png)

### Additional Information
everything is on default settings

**Comment by Margen67** [comment] 2020-05-12 20:17
Duplicate of #184

**Closed by Margen67** 2020-05-12 20:17 UTC
