### ISSUE TITLE
Futurama regression

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#198] opened 2017-08-22 08:18 UTC
_From @jarupxx on March 4, 2017 8:16_

Futurama crashes in latest build, also 67c37feebd014a9e2725409f162e327bc24b0d8f, but in version 231e924bd13ae31a77a14b1f8128541a562ebaaa showed reach in-menu. In very older versions, reached in-game.

What is the reason for the crash in latest build? I do not know.
but I know the reason for not reached in-game in this version 231e924bd13ae31a77a14b1f8128541a562ebaaa. Because false detection 5344 version of the SetMinDistance function. False detection is resolved at #208.

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#212_

**Comment by PatrickvL** [comment] 2017-08-22 08:18
Issue #223 might fix this regression

**Comment by PatrickvL** [comment] 2017-08-22 08:18
_From @LukeUsher on March 13, 2017 22:0_

Managed to get it to boot, however something is still very broken (Futurama PAL Version)
Also it still crashes when attempting to progress further than menus.

![image](https://cloud.githubusercontent.com/assets/740003/23877036/429811ae-0838-11e7-942f-6691a8050c63.png)

**Comment by PatrickvL** [comment] 2017-08-22 08:18
_From @bhodg22 on March 29, 2017 2:38_

![untitled](https://cloud.githubusercontent.com/assets/5080749/24436057/88e3f2c2-147c-11e7-8600-b799ed34928f.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/877633/KrnlDebug.txt)
Tried a slightly older build from march 23 with same results

**Comment by PatrickvL** [comment] 2017-08-22 08:18
Can you re-test this with build https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/6e250dc345f0c538238070ebf9b933dba348a114 or later?

**Comment by PatrickvL** [comment] 2017-08-22 08:18
_From @bhodg22 on March 30, 2017 23:13_

![untitled](https://cloud.githubusercontent.com/assets/5080749/24529963/39ac1b72-15f2-11e7-9abf-2c9890cb72ef.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/884033/KrnlDebug.txt)

**Comment by PatrickvL** [comment] 2017-08-22 08:18
Bummer. I'd hoped it had improved. Thanks for testing anyway!

**Comment by PatrickvL** [comment] 2017-09-18 11:01
@Cxbx-Reloaded/issue-maintainers : Please merge #198, #128 and #71 into one issue.

**Comment by CakeLancelot** [comment] 2017-09-18 15:32
Duplicate of #71. I've added a note in the post about variations in game versions, settings, etc. This can be closed.

**Closed by CakeLancelot** 2017-09-18 15:32 UTC
Labels: state-booting, state-crashes, type-retail
