### ISSUE TITLE
Halo: Combat Evolved

### ISSUE THREAD

**Issue by bazik210** [Cxbx-Reloaded/game-compatibility#945] opened 2020-03-06 19:19 UTC
![halo](https://user-images.githubusercontent.com/8839910/76114987-558c2f00-5ff8-11ea-921c-d4441d14d4a3.jpg)
Instead of menu i got this... GF GTX 670

**Comment by GXTX** [comment] 2020-03-06 19:48
Duplicate of #95, please search before opening new issues.

**Closed** 2020-03-06 20:37 UTC
Labels: duplicate, invalid
