### ISSUE TITLE
Baldur's Gate Dark Alliance pal

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#245] opened 2017-08-28 09:09 UTC
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258045/Xbe.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255898/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255900/KrnlDebug.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by ergo720** [comment] 2017-08-28 10:41
Possible duplicate of #243 but no xbe.txt is provided to check for it

**Comment by ergo720** [comment] 2017-08-28 20:37
Ok, the xbe dumps of this and #243 are identical, so this is a duplicate

**Closed** 2017-08-28 20:40 UTC
