### ISSUE TITLE
ALIAS

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#221] opened 2017-08-28 08:42 UTC
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255646/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255647/KrnlDebug.txt)
[PSDef000.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255648/PSDef000.txt)
[PSDef001.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255650/PSDef001.txt)
[PSDef002.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255651/PSDef002.txt)
[PSDef003.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255652/PSDef003.txt)
[PSDef004.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255653/PSDef004.txt)
[PSDef005.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255654/PSDef005.txt)
[PSDef006.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255649/PSDef006.txt)
[PSDef007.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255655/PSDef007.txt)
[PSDef008.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255656/PSDef008.txt)
[PSDef009.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255657/PSDef009.txt)
[PSDef010.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255658/PSDef010.txt)
[PSDef011.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255659/PSDef011.txt)
[PSDef012.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255660/PSDef012.txt)
[PSDef013.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255661/PSDef013.txt)
[PSDef014.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255662/PSDef014.txt)
[PSDef015.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255663/PSDef015.txt)
[PSDef016.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255664/PSDef016.txt)
[PSDef017.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255665/PSDef017.txt)
[PSDef018.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255666/PSDef018.txt)
[PSDef019.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255667/PSDef019.txt)
[PSDef020.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255668/PSDef020.txt)
[PSDef021.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255669/PSDef021.txt)
[PSDef022.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255670/PSDef022.txt)
[PSDef023.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255671/PSDef023.txt)
[PSDef024.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255672/PSDef024.txt)
[PSDef025.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255673/PSDef025.txt)
[PSDef026.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255674/PSDef026.txt)
[PSDef027.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255675/PSDef027.txt)
[PSDef028.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255676/PSDef028.txt)
[PSDef029.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255677/PSDef029.txt)
[PSDef030.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255678/PSDef030.txt)
[PSDef031.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255679/PSDef031.txt)
[PSDef032.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255680/PSDef032.txt)
[PSDef033.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255681/PSDef033.txt)
[PSDef034.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255682/PSDef034.txt)
[PSDef035.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255683/PSDef035.txt)
[PSDef036.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255684/PSDef036.txt)
[PSDef037.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255685/PSDef037.txt)
[PSDef038.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255686/PSDef038.txt)
[PSDef039.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255687/PSDef039.txt)
[PSDef040.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255688/PSDef040.txt)
[PSDef041.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255689/PSDef041.txt)
[PSDef042.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255690/PSDef042.txt)
[PSDef043.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255691/PSDef043.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Voxel9** [comment] 2017-08-28 09:20
Duplicate of #22

**Closed** 2017-08-28 09:45 UTC
