### ISSUE TITLE
Chase

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#310] opened 2017-08-28 19:53 UTC
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258113/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258116/KrnlDebug.txt)
[PSDef000.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258114/PSDef000.txt)
[PSDef001.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258117/PSDef001.txt)
[PSDef002.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258118/PSDef002.txt)
[PSDef003.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258115/PSDef003.txt)
[PSDef004.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258119/PSDef004.txt)
[PSDef005.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258120/PSDef005.txt)
[PSDef006.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258121/PSDef006.txt)
[PSDef007.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258123/PSDef007.txt)
[PSDef008.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258122/PSDef008.txt)
[PSDef009.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258124/PSDef009.txt)
[PSDef010.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258125/PSDef010.txt)
[PSDef011.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258126/PSDef011.txt)
[PSDef012.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258127/PSDef012.txt)
[PSDef013.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258128/PSDef013.txt)
[PSDef014.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258129/PSDef014.txt)
[PSDef015.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258130/PSDef015.txt)
[PSDef016.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258131/PSDef016.txt)
[PSDef017.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258132/PSDef017.txt)
[PSDef018.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258133/PSDef018.txt)
[PSDef019.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258134/PSDef019.txt)
[PSDef020.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258135/PSDef020.txt)
[PSDef021.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258136/PSDef021.txt)
[PSDef022.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258137/PSDef022.txt)
[PSDef023.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258138/PSDef023.txt)
[PSDef024.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258139/PSDef024.txt)
[PSDef025.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258140/PSDef025.txt)
[PSDef026.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258141/PSDef026.txt)
[PSDef027.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258142/PSDef027.txt)
[PSDef028.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258143/PSDef028.txt)
[PSDef029.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258144/PSDef029.txt)
[PSDef030.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258145/PSDef030.txt)
[PSDef031.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258146/PSDef031.txt)
[PSDef032.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258147/PSDef032.txt)
[PSDef033.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258148/PSDef033.txt)
[PSDef034.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258149/PSDef034.txt)
[PSDef035.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258150/PSDef035.txt)
[PSDef036.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258151/PSDef036.txt)
[PSDef037.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258152/PSDef037.txt)
[PSDef038.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258153/PSDef038.txt)
[PSDef039.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258154/PSDef039.txt)
[PSDef040.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258155/PSDef040.txt)
[PSDef041.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258156/PSDef041.txt)
[PSDef042.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258157/PSDef042.txt)
[PSDef043.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258158/PSDef043.txt)
[PSDef044.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258159/PSDef044.txt)
[PSDef045.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258160/PSDef045.txt)
[PSDef046.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258161/PSDef046.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258162/Xbe.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by ergo720** [comment] 2017-08-28 20:20
Duplicate of #45

**Closed** 2017-08-28 20:31 UTC

**Comment by Margen67** [comment] 2020-08-16 05:23
Different version, but ambigous description, so this will remain closed until someone posts a new report here.
