### ISSUE TITLE
Full Spectrum Warrior: Ten Hammers [TQ-248] [1.01]

### ISSUE THREAD

**Issue by bryce13950** [Cxbx-Reloaded/game-compatibility#1019] opened 2020-07-11 20:45 UTC
### Description

The game immediately crashes without any error message showing

```

```

### Dumps

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4907570/Xbe.txt)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4907569/KrnlDebug.txt)

### Status
**Previous behavior:** 

None Reported

**Current behavior:**

Not Booting

**Comment by bryce13950** [comment] 2020-07-18 09:47
This is a duplicats of #1020 now

**Comment by Margen67** [comment] 2020-07-19 03:14
Duplicate of #1020

**Closed by Margen67** 2020-07-19 03:14 UTC
Labels: meta-duplicate
