### ISSUE TITLE
Final Fight Arcade [Final Fight X Streetwise] [CC-019] [1.01]

### ISSUE THREAD

**Issue by MarcoLoves360** [Cxbx-Reloaded/game-compatibility#719] opened 2018-04-15 19:33 UTC
**Description**
FinalF.xbe (Final Fight Arcade) 

**Dumps**
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1913218/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1913228/KrnlDebug.txt)

**Status**
Playable ~20 fps

Previous behavior:
none

Current behavior:
Wrong pallet colors, sometimes flashes, it seems it reverse back to correct colors when the screen is fading out or going to the next area, 1/2 frames then it goes back to wrong palette. 

**Screenshots**
![image](https://user-images.githubusercontent.com/30830822/38782416-04763936-40eb-11e8-9154-0555818b3d26.png)
![image](https://user-images.githubusercontent.com/30830822/38782436-45369d26-40eb-11e8-879c-0054aab2c27f.png)

**Additional Information**

build 0b63bfd0

**Comment by CakeLancelot** [comment] 2018-04-15 20:35
Appears to be https://github.com/Cxbx-Reloaded/game-compatibility/issues/90, though I'll admit the wording for the title of that issue isn't the best and may not show up in searches... I'll either move everything over there and change the title to something more fitting or make this the new main issue.

**Comment by Margen67** [comment] 2020-08-09 03:51
Duplicate of #90

**Closed by Margen67** 2020-08-09 03:51 UTC
Labels: meta-duplicate
