### ISSUE TITLE
BLiNX the time sweeper PAL

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#266] opened 2017-08-28 09:27 UTC
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256086/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256087/KrnlDebug.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Voxel9** [comment] 2017-08-28 09:29
Duplicate of #184

**Closed** 2017-08-28 09:36 UTC
