### ISSUE TITLE
Smashing Drive

### ISSUE THREAD

**Issue by SonicThePS4** [Cxbx-Reloaded/game-compatibility#780] opened 2018-05-25 17:43 UTC
### Description

This has a black screen while the Smashing Drive Intro is still going. & It has this bug/glitch lighting in the middle of the Smashing Drive Game Play. But the Audio System is still good. 

```

```

### Dumps 
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2040404/Xbe.txt)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2040405/KrnlDebug.txt)

### Status
**Previous behavior:** 

**Current behavior:**

### Screenshots

![image](https://user-images.githubusercontent.com/39503785/40558279-d05a79be-6020-11e8-8387-d5bd8588a7c1.png)

![untitled](https://user-images.githubusercontent.com/39503785/40557980-e8aa83fc-601f-11e8-991f-f0c19bd7bfd8.png)

**Comment by CakeLancelot** [comment] 2018-05-25 17:53
Duplicate of #426, please search to see if there's an existing issue before creating another one.

**Comment by gandalfthewhite19890404** [comment] 2018-05-25 17:53
AMD GPU has this issue, Geforce runs fine. Also wined3d fixes issue, but its not a solution, just hack.

**Closed by CakeLancelot** 2018-05-25 17:53 UTC
