### ISSUE TITLE
Area 51 [MW-005] [1.03]

### ISSUE THREAD

**Issue by ghost** [Cxbx-Reloaded/game-compatibility#357] opened 2017-09-14 18:34 UTC
https://en.wikipedia.org/wiki/Area_51_(2005_video_game)

### Description

Game is not supported by HLE

### Dumps 

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1304087/Xbe.txt)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1304093/KrnlDebug.txt)

### Status
**Previous behavior:**

**Current behavior:**

### Screenshots 

![capture](https://user-images.githubusercontent.com/31968468/30447334-1cfa5cc6-99cf-11e7-9761-71fcca036a2b.PNG)

### Additional Information

**Information from #14:**
[Area51.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1213259/Area51.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210191/KrnlDebug.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1210189/CxbxDebug.txt)

**Comment by CakeLancelot** [comment] 2017-09-14 20:40
Duplicate of #14 , though this one is way more detailed. You could either post your info there or we could just keep this issue instead and close the original.

**Comment by PatrickvL** [comment] 2017-09-14 21:12
I've closed the other. Please copy anything worth keeping from there into this issue.

**Closed** 2020-07-30 11:57 UTC
Labels: region-japan, region-other, region-us-canada, state-unverified, type-retail, uses-ltcg, xdk-5849
