### ISSUE TITLE
Halo - Combat Evolved MS-004 v1.01

### ISSUE THREAD

**Issue by FranciscoSam** [Cxbx-Reloaded/game-compatibility#936] opened 2020-01-25 01:06 UTC
### Description
Goes to Menu.Several Graphical issues.But Hangs on Black Screen

### Status
**Previous behavior:** 
None Reported

**Current behavior:**
Black Screen and Graphical Issues

### Screenshots

![2020_01_24_20_47_30_656x536](https://user-images.githubusercontent.com/52464858/73113904-d251c680-3eec-11ea-9fcd-369af947414b.jpg)
![2020_01_24_20_48_26_656x536](https://user-images.githubusercontent.com/52464858/73113918-e09fe280-3eec-11ea-8449-41cf9f3dd57d.jpg)
![2020_01_24_20_48_29_656x536](https://user-images.githubusercontent.com/52464858/73113921-e7c6f080-3eec-11ea-9e71-b838b94638e1.jpg)
![2020_01_24_20_48_35_656x536](https://user-images.githubusercontent.com/52464858/73113925-ebf30e00-3eec-11ea-84f1-a4ebe7fd4c64.jpg)
![2020_01_24_20_48_49_656x536](https://user-images.githubusercontent.com/52464858/73113954-20ff6080-3eed-11ea-9671-1eccc04a5df1.jpg)
![2020_01_24_20_48_51_656x536](https://user-images.githubusercontent.com/52464858/73113956-252b7e00-3eed-11ea-8e19-9e5fd3052b89.jpg)

**Comment by LanHikariDS** [comment] 2020-01-25 06:01
We already have an issue for Halo, though
https://github.com/Cxbx-Reloaded/game-compatibility/issues/95

**Comment by FranciscoSam** [comment] 2020-01-25 12:32
i got a different version

**Comment by illusion98** [comment] 2020-01-28 09:19
Duplicate of #95

**Closed** 2020-01-28 09:24 UTC
Labels: issue-video, state-unresponsive, type-retail, xbe-dump-needed
