### ISSUE TITLE
Shadow The Hedgehog 

### ISSUE THREAD

**Issue by MiniGamer2015** [Cxbx-Reloaded/game-compatibility#959] opened 2020-04-27 20:33 UTC
### Description
When starting the emulation, the logos show up, then the audio of the intro shows up but not the video of the intro, then when you press start, the "Load game" thing shows up but glitched. The menus seem to be fine, when you create a new game, the screen frezees but the subtitles and the audio show up, then when the cutscene ends, there's a black screen but with the UI of the game

### Status
**Previous behavior:** 
partially-working

**Current behavior:**
state-interactive

### Additional Information
I didnt enable any speedhacks, im using the version uploaded on April 27, 2020

![2](https://user-images.githubusercontent.com/43279290/80418043-2a61e580-88ad-11ea-8779-d250f02fea67.png)
![3](https://user-images.githubusercontent.com/43279290/80418050-2b931280-88ad-11ea-9746-bbd3b5840765.png)
![4](https://user-images.githubusercontent.com/43279290/80418056-2c2ba900-88ad-11ea-8a10-8fef71853ff0.png)
![5](https://user-images.githubusercontent.com/43279290/80418059-2cc43f80-88ad-11ea-81b4-b9a83fda3102.png)
![6](https://user-images.githubusercontent.com/43279290/80418061-2d5cd600-88ad-11ea-885d-1916945f8f61.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4541870/KrnlDebug.txt)
![1](https://user-images.githubusercontent.com/43279290/80418065-2e8e0300-88ad-11ea-8fab-653dee61964a.png)

**Comment by Margen67** [comment] 2020-04-27 22:46
Duplicate of #476

**Closed by Margen67** 2020-04-27 22:46 UTC
