### ISSUE TITLE
Xbox Dashboard "Fail to init XboxRenderStates" on build 0f030cf2

### ISSUE THREAD

**Issue by ParzivalWolfram** [Cxbx-Reloaded/game-compatibility#924] opened 2019-10-10 05:42 UTC
### Description

Xbox Dashboard 1.00.5659.03 V1.4 throws "Failed to create XboxRenderStates" immediately after starting emulation

```
Received Fatal Message:
* Failed to init XboxRenderStates
```

### Dumps 

(Creating issue on mobile, please accept Pastebin in lieu of actual files)
Xbe dump: https://pastebin.com/D1urxgFV
KrnlDump: https://pastebin.com/96ewDdPs

### Status
**Previous behavior:** 

None Reported
**Current behavior:**

Crash upon emulation start (give or take a couple seconds for fullscreen init) with popup described above.

### Screenshots

N/A

### Additional Information

Cxbx build 0f030cf2 (October 8, 2019)
No hacks enabled

NOTE: Behavior also present when booting Sega GT 2002 but not when booting Jet Set Radio Future.

EDIT: Turning on LLE GPU makes the Dashboard jump to Error 21.

**Comment by LukeUsher** [comment] 2019-10-10 07:11
Dashboards greater than 4920 are not currently supported, but SEGA GT is indeed a regression. 

Also please do not create issues for experimental builds. The build you are using is incomplete code that hasn’t been merged yet. Bug reports should be made with the latest development build. 

If an issue is specific to the experimental code, then the issue should be posted in the relevant pull-request so we can investigate. 

Also for game-compatibility issues, please follow the standard issue format in future.

This issue will likely be closed due to 1. Being created from incomplete code, not the latest development build 
2. Not following the correct issue format

**Comment by ParzivalWolfram** [comment] 2019-10-10 07:42
Where can I find said latest dev build? I pulled this copy from your
buildbot, which seems to only be running from master...?

**Comment by LukeUsher** [comment] 2019-10-10 07:48
You can download the latest dev build by following the link on the readme, under the 'automated builds' section

![image](https://user-images.githubusercontent.com/740003/66549149-94e24c80-eb3a-11e9-9393-2b89e33e4ff2.png)

The build bot builds all branches and pull-requests, incomplete or not, so we can auto-reject builds that fail, or make it easier for people to test experimental stuff.

But if you want to test experimental stuff, you should get them from the pull-request so you know what you're testing.

**Comment by ParzivalWolfram** [comment] 2019-10-10 08:03
I see. My bad.

Additionally, with some tinkering, I figured out that turning on the LLE
GPU allows the Xbox Dashboard to load, but in an extremely visually
corrupted state. With Autoplay on, LLE GPU isn't needed and it'll skip
straight into Sega GT, but it crashes shortly in with the same error as
people had with JSRF.

This info invalidates this, but still good to document.

**Comment by PatrickvL** [comment] 2019-11-18 12:29
Please move relevant information to https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues and/or https://github.com/Cxbx-Reloaded/game-compatibility/issues/714

Closing this according to the "only report unique titles" rule that applies here.

**Closed by PatrickvL** 2019-11-18 12:29 UTC
