### ISSUE TITLE
Capcom Fighting Evolution [CC-016] [1.01]

### ISSUE THREAD

**Issue by PipoCrazy** [Cxbx-Reloaded/game-compatibility#1000] opened 2020-06-16 09:38 UTC
### Description
The only problem that I have encountered is that the sprites are glitchy. The fighters look deformed in game. Music and menus OK.

### Dumps
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4785722/Xbe.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4785740/KrnlDebug.txt)

### Status
'None reported'

**Current behavior:**
Bad sprites.

### Screenshots
![1](https://user-images.githubusercontent.com/56910468/84758515-ef6e5b00-af9b-11ea-82df-e4ce4ab83bd8.jpg)
![2](https://user-images.githubusercontent.com/56910468/84758522-f1381e80-af9b-11ea-93dd-0c6902153585.jpg)
![3](https://user-images.githubusercontent.com/56910468/84758525-f2694b80-af9b-11ea-96fa-5f145e00aecb.jpg)
![4](https://user-images.githubusercontent.com/56910468/84758529-f4330f00-af9b-11ea-9210-1f6e1f41ba38.jpg)

### Additional Information
Cxbx-Reloaded Version f1d09af (Jun  8 2020)

**Comment by ObiKKa** [comment] 2020-08-17 19:48
What's the difference between this new page and this old issue #285 added 3 years ago on Aug 28, 2017? They both have the same title and ID. Just this issue has more regional labels (Japan and debug editions).
The original post is basic, but another user provided a nice update with screenshots on Apr 16, 2019.

**Comment by Margen67** [comment] 2020-08-17 22:50
Duplicate of #285

**Closed by Margen67** 2020-08-17 22:50 UTC
Labels: meta-duplicate
