### ISSUE TITLE
QUANTUM REDSHIFT

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#311] opened 2017-08-28 19:54 UTC
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258163/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258164/KrnlDebug.txt)
[PSDef000.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258166/PSDef000.txt)
[PSDef001.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258169/PSDef001.txt)
[PSDef002.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258167/PSDef002.txt)
[PSDef003.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258168/PSDef003.txt)
[PSDef004.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258165/PSDef004.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258170/Xbe.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by ergo720** [comment] 2017-08-28 20:16
Duplicate of #9 and #194

**Comment by Voxel9** [comment] 2017-08-28 20:28
After all we talked about on Discord, and you _still_ can't use the search function? Come on, man...

**Closed by Voxel9** 2017-08-28 20:28 UTC
