### ISSUE TITLE
cel damage

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#288] opened 2017-08-28 09:52 UTC
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256369/CxbxDebug.txt)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256370/KrnlDebug.txt)
[PSDef000.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256371/PSDef000.txt)
[PSDef001.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256372/PSDef001.txt)
[PSDef002.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256373/PSDef002.txt)
[PSDef003.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256374/PSDef003.txt)
[PSDef004.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256375/PSDef004.txt)
[PSDef005.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256376/PSDef005.txt)
[PSDef006.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256377/PSDef006.txt)
[PSDef007.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256378/PSDef007.txt)
[PSDef008.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1256379/PSDef008.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by Voxel9** [comment] 2017-08-28 09:54
Duplicate of #64

**Closed by Voxel9** 2017-08-28 09:54 UTC
