### ISSUE TITLE
AIRFORCE DELTA II [4B4E0002]

### ISSUE THREAD

**Issue by fatjohnny118** [Cxbx-Reloaded/game-compatibility#219] opened 2017-08-28 08:35 UTC
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1258070/Xbe.txt)
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255626/CxbxDebug.txt)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1255630/KrnlDebug.txt)

videos uploaded after i upload all my logs 

CREDIT GOES TO ALL INVOLVED NOT JUST ME I ONLY POSTING VIDS AND LOGS

https://www.youtube.com/channel/UCrChZD2sqKLWRxX33IjeRjg

**Comment by ObiKKa** [comment] 2020-05-11 06:24
Duplicate of #24.

**Closed** 2020-05-11 06:25 UTC
Labels: duplicate
